# Generated by Django 6.1.1 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(choices=[(0, 'Generalidades e Informação: Obras gerais, enciclopédias, jornais e biblioteconomia.'), (100, 'Filosofia e Psicologia: Ética, lógica e investigações sobre a mente humana.'), (200, 'Religião e Teologia: Mitologia, teologia e estudos sobre crenças e religiões.'), (300, 'Ciências Sociais e Direito: Política, economia, sociologia, educação e leis.'), (400, 'Linguística e Idiomas: Gramáticas, dicionários e estudos de línguas.'), (500, 'Ciências Puras (Exatas e Naturais): Matemática, física, química, biologia e astronomia.'), (600, 'Ciências Aplicadas (Tecnologia): Medicina, engenharia, agricultura e administração.'), (700, 'Artes e Recreação: Pintura, música, arquitetura, esportes e lazer.'), (800, 'Literatura: Poesia, romances, contos, crônicas e crítica literária.'), (900, 'História e Geografia: Biografias, viagens e acontecimentos históricos.')], default=0, verbose_name='Categoria')),
                ('tipo', models.CharField(choices=[('D1', 'Digital'), ('F2', 'Fisico')], default='D1', max_length=2, verbose_name='Tipo')),
                ('livro', models.ManyToManyField(to='acervo.livro', verbose_name='livro')),
            ],
        ),
    ]
